services:
  # API server
  api-server:
    env_file: .env
    image: lewis-express-licitalab-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    links:
      - postgres-server
    depends_on:
      - postgres-server

  # service of database
  postgres-server:
    env_file: .env
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DEV_DB_USERNAME}
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
